apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-estadisticas-deployment
  labels:
    app: api-estadisticas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-estadisticas
  template:
    metadata:
      labels:
        app: api-estadisticas
    spec:
      containers:
        - name: api-estadisticas
          image: localhost:5000/api_estadisticas
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_HOST
              value: "192.168.1.84"
            - name: POSTGRES_PASSWORD
              value: "pablo1984"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: api-estadisticas-servicio
spec:
  type: LoadBalancer
  selector:
    app: api-estadisticas
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
